### ISSUE TITLE
release new version (for pre-commit hook)

### ISSUE THREAD

**Issue by chrisjsewell** [myint/rstcheck#69]
I think two years is long enough to wait for a new version lol!
Specifically though for use with the new pre-commit integration  #63, which you can only use with `rev: master` at present

**Comment by chrisjsewell** [comment]
FYI another "issue" with the pre-commit hook is sphinx integration. You might want to mention in the README that, to include sphinx the pre-commit environment, you can do:

```yaml
  - repo: https://github.com/myint/rstcheck
    rev: ''
    hooks:
    - id: rstcheck
      additional_dependencies:
        - sphinx==2.4.4
```

**Comment by peterjc** [comment]
If you try to use an older release with pre-commit like v3.3.1, you'll get a slightly cryptic error like this:

```
$ pre-commit install-hooks
An error has occurred: InvalidManifestError: 
=====> /Users/XXX/.cache/pre-commit/repo_dlvm5iz/.pre-commit-hooks.yaml does not exist
Check the log at /Users/XXX/.cache/pre-commit/pre-commit.log
```

The randomly named folder is the cache of rstcheck, which lacks the YAML file.

**Comment by Cielquan** [comment]
> If you try to use an older release with pre-commit like v3.3.1, you'll get a slightly cryptic error like this:
> 
> ```
> $ pre-commit install-hooks
> An error has occurred: InvalidManifestError: 
> =====> /Users/XXX/.cache/pre-commit/repo_dlvm5iz/.pre-commit-hooks.yaml does not exist
> Check the log at /Users/XXX/.cache/pre-commit/pre-commit.log
> ```
> 
> The randomly named folder is the cache of rstcheck, which lacks the YAML file.

The reason for the error you are seeing ist, that the `.pre-commit-hooks.yaml` file which holds the config for `pre-commit` on the repositories side was added after version 3.3.1. So if you specify 3.3.1 as target you get the error above.


---


I just made a fork and added a tag `3.4.0` for the current master (https://github.com/myint/rstcheck/commit/3f92957478422df87bd730abde66f089cc1ee19b): https://github.com/Cielquan/rstcheck/releases/tag/v3.4.0

**However this is only thought as a temporary workaround and I do not have the intention of keeping it updated.** 

So you can use `rstcheck` with:

`.pre-commit-config.yaml`:
```yaml
repos:
  - repo: https://github.com/Cielquan/rstcheck
    rev: 3f92957478422df87bd730abde66f089cc1ee19b  # frozen: 3.4.0
    hooks:
      - id: rstcheck
```

**Comment by peterjc** [comment]
My comment was to record the error message here, in the hope of helping other people hitting it. And as a gentle reminder that rstcheck would benefit from a point release.

For my workaround, I went for this alternative - using the hash of the commit which added the required file:

```yaml
-   repo: https://github.com/myint/rstcheck
    rev: 3f92957478422df87bd730abde66f089cc1ee19b
    hooks:
    -   id: rstcheck
        args: [--report=warning]
```
